version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "avelino"
    labels:
      - "npm"
      - "dependencies"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "avelino"
    labels:
      - "github-actions"
      - "dependencies"
